apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-web-app
spec:
  replicas: 2
  selector:
    matchLabels: { app: node-web-app }
  template:
    metadata:
      labels: { app: node-web-app }
    spec:
      containers:
        - name: web
          image: ishinis223075053/node-web-app:db
          ports: [{ containerPort: 8080, name: http }]
          env:
            - name: MONGO_URI
              value: "mongodb://user:pass@mongo-svc:27017/appdb?authSource=admin"
          readinessProbe:
            httpGet: { path: /health, port: http }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /health, port: http }
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: node-web-app-svc
spec:
  type: NodePort
  selector: { app: node-web-app }
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
      name: http
